### ISSUE TITLE
Mandatory and Bonus files should have the same content

### ISSUE THREAD

**Issue by nwhean** [shawnteh1711/get_next-line#1]
https://github.com/shawnteh1711/get_next-line/blob/62656f2880511d7d481adaafc4201da29eebc0d5/get_next_line.c#L17

It's alright to submit the same file content for both mandatory and bonus. Just make sure the file names are correct, and referring to the right header.

**Comment by shawnteh1711** [comment]
What is the issue?

**Comment by nwhean** [comment]
By just having one version, you can just amend one file only when you make changes. Just remember to duplicate a bonus version and change the header when you want to submit.
