### ISSUE TITLE
Probably better to use ssize_t

### ISSUE THREAD

**Issue by nwhean** [shawnteh1711/get_next-line#2]
https://github.com/shawnteh1711/get_next-line/blob/62656f2880511d7d481adaafc4201da29eebc0d5/get_next_line.c#L38

You are doing an implicit integer demotion here. Should try to avoid this, for best practice.

**Comment by shawnteh1711** [comment]
Ya, ssize_t seem to be better and follow the read() standard output data type. The range value of int is -2,147,483,648 to 2,147,483,647, ssize_t is from -1 to ssize_max. But what actually is the ssize_max? By implicit integer demotion, do you mean the output from read() might lost some information when convert from ssize_t to int implicitly?

**Comment by shawnteh1711** [comment]
After checking, it seems like ssize_max depends on the POSIX system. In 32 bits machine, it is 2^31, while in 64 bits machine, it is 2^63.

**Comment by nwhean** [comment]
Yes, that's why there might be integer demotion, something that we should try to avoid as much as we can, even thought it might seem like it's not causing any harm in your current program.
